version: "3"

services:
  server:
    build: "./backend"
    expose:
      - ${BACKEND_PORT}
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - webappnetwork

  client:
    build: "./frontend"
    expose:
      - ${FRONT_END_PORT}
    env_file:
      - .env
    ports:
      - ${FRONT_END_PORT}:${FRONT_END_PORT}
    links:
      - server
    networks:
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge
